### PR TITLE
Feature/i18n de

### PR DESCRIPTION
**Pull request by Thesicstar**

### CODE REVIEW

**Comment by Leecason** [comment]
Thanks for your PR, please read the [contribution guide](https://github.com/Leecason/element-tiptap/tree/master#-contributing-) then resubmit it. thank you

**Comment by Leecason** [comment]
Hey, Thesicstar.
Recently I added some new features with image, the current change of this pr is outdated, could you please update it and submit this pr again. Before you submit a pr please read the [contribution guide](https://github.com/Leecason/element-tiptap/tree/master#-contributing-).
I'm really looking forward to this i18n. Thank you in advance

**Comment by Thesicstar** [comment]
Hey there, sorry for the delay,
I updated the commit messages, merged your develop into my feature branch and updated the base target. This PR should now be up-to-date. Please let me know if there is anything else I need to change!

**Comment by Leecason** [comment]
Thank you, i will add CONTRIBUTING.md.
I didn't see the translation of [this part](https://github.com/Leecason/element-tiptap/blob/master/src/i18n/en/index.ts#L55-L100) in your changes, please check it again.
There are 6 commits for this, can you reduce it a little bit ?  If not, you can resubmit a pr.
Thank you again

**Comment by Thesicstar** [comment]
Redid this PR and added new translations; See #41

**Pull request closed without merging**
