### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by LPABelgium**
First time I contribute, so be cool ^^ Hope I've done all things right

### CODE REVIEW

**Comment by Leecason** [comment]
Looks Good To Me! 👍
Thanks for your pr!

**Comment by LPABelgium** [comment]
Thanks ;)

**Comment by LPABelgium** [comment]
Well well well... hum...now that I see it lives, some stuff are'nt well translated or semanticly correct.

So How could I update those incorrect translations ? 
And what the goal of "semantic-release" ? Can this allow me to modify the translations without going through a PR again?

As I said, I'm a newbee into "PR" and contribution on a package, be indulgent :D
@Leecason

**Comment by Leecason** [comment]
It doesn't matter. You should submit a new pr just like before.

**Pull request merged**
