### PR TITLE
fix wrong polish translation

### PR DESCRIPTION
**Pull request by chlewicki**
resubmit PR

### CODE REVIEW

**Comment by Leecason** [comment]
https://github.com/Leecason/element-tiptap/pull/37

**Comment by Leecason** [comment]
Thank you!

**Comment by chlewicki** [comment]
Great! How often do you merge to master?

**Comment by Leecason** [comment]
Already released in [1.17.1](https://github.com/Leecason/element-tiptap/releases/tag/%401.17.1)
Because i update your commit message with semantic message for CI to make CHANGELOG.md, so the commit hash changed, the ci robot will not leave a release comment in this PR.
Thank you~

**Pull request merged**
